// The site's texts, in English: the node cabinet, the link page (l_) and the Support page (support_). The terms
// shared with QNet Wallet and the QNet extension take their wording. Server and client code import this module
// directly; the tests read it too.

export const TEXTS = {
  // Shell
  cabinet_title: 'My node',
  cabinet_description: 'Connect your QNet wallet, activate a light node or a super node, and follow its status.',
  eligibility: 'A light node runs on one phone or tablet at a time, in QNet Wallet; a super node runs on a server with the QNet node software.',
  nav_label: 'My node sections',
  nav_overview: 'Overview',
  nav_activate: 'Activate',
  nav_device: 'Device',
  nav_history: 'History',
  wallet_from_qr: 'QNet Wallet shared this address through a QR request. Compare it with the wallet the app shows.',
  go_home: 'Open My node',

  // Connecting the wallet
  connect_title: 'Connect your wallet',
  connect_lead: 'Choose one way. Your keys stay in your wallet: this site never holds them.',
  connect_app_here: 'QNet Wallet on this phone',
  connect_app_here_note: 'QNet Wallet opens and asks you to confirm. Then come back to this page.',
  connect_app_qr: 'QNet Wallet on your phone',
  connect_app_qr_note: 'A QR code appears. Scan it with your phone\'s camera: QNet Wallet opens and asks you to confirm.',
  connect_ext: 'QNet extension on this computer',
  connect_ext_note: 'The extension asks you to approve. Its window may open behind this one.',
  connect_get_ext: 'Using a computer? The QNet extension connects here too.',
  connect_get_app: 'No QNet Wallet on this phone yet? Install it first, then come back to this page.',
  connect_get_app_link: 'Get QNet Wallet',
  connect_view_title: 'View by address',
  connect_view_note: 'Only to look: type a QNet address to see its node. Nothing can be changed this way.',
  wallet_extension_waiting: 'Confirm in the extension window. It may have opened behind this one.',
  wallet_extension_failed: 'The QNet extension did not share its wallet. Unlock it, confirm in its window and try again; if this keeps happening, update the QNet extension and reload this page.',
  wallet_enter_label: 'QNet address',
  wallet_enter_submit: 'View',
  wallet_enter_invalid: 'This is not a QNet address.',
  wallet_ask_app: 'Ask QNet Wallet',
  wallet_ask_app_note: 'QNet Wallet shows the request and shares this wallet\'s QNet and Solana addresses. Nothing else leaves it.',
  wallet_other_device: 'Use another device: show the QR',
  wallet_remembered: 'This browser remembers your wallet until you press Disconnect.',
  action_activate_light: 'Activate a light node',
  action_activate_super: 'Activate a super node',

  // The connected wallet
  wallet_label: 'Your wallet',
  wallet_copy_hint: 'Click or tap the address to copy it.',
  wallet_copy_label: 'Copy the wallet address',
  wallet_source_extension: 'Connected with the QNet extension.',
  wallet_source_app: 'Connected with QNet Wallet on this device.',
  wallet_source_app_qr: 'Connected with QNet Wallet by QR code.',
  wallet_source_entered: 'View only: you typed this address.',
  wallet_disconnect: 'Disconnect',
  connect_first: 'You are only viewing this address. To make changes, connect the wallet itself.',
  connect_first_button: 'Connect your wallet',

  // Where the wallet is on the way to a running node
  progress_label: 'Your progress',
  progress_connect: 'Connect',
  progress_activate: 'Activate',
  progress_link: 'Link a device',
  progress_server: 'Run the server',
  progress_running: 'Running',
  progress_done: 'done',
  progress_now: 'now',

  // Overview
  overview_title: 'Your node',
  epoch_note: 'The network checks each node once per epoch, a period of about 4 hours.',

  // The next step after an activation: the node recorded on the QNet network, the phone linked, the node running
  next_record_title: 'Recording your node on the QNet network',
  next_step_burn: 'Burned on Solana',
  next_step_burn_pending: 'Burn sent to Solana, not final yet',
  next_step_record: 'Recorded on the QNet network',
  next_step_link: 'Linked to your phone',
  next_recording: 'The QNet extension records your node now. This usually takes one to three minutes; this page checks by itself every few seconds and moves on to linking your phone as soon as the network lists the node.',
  next_phone_ready: 'While the network records it, get your phone or tablet ready:',
  next_network_down: 'The QNet network did not answer just now. This page asks again by itself every few seconds.',
  next_waited_now: 'Started less than a minute ago.',
  next_waited: 'Waiting {minutes} min so far.',
  next_record_again_lead: 'Still not recorded after a few minutes? Ask the extension to record it again and confirm in its window. This wallet already has its activation, so nothing is burned again.',
  next_record_again_lead_pending: 'Still not recorded after a few minutes? Ask the extension again and confirm in its window. It first checks the burn it sent, and its window says so if a new burn would be needed.',
  next_record_again: 'Record on the network',
  next_record_asked: 'The extension is recording the node again. This page moves on to linking your phone as soon as the QNet network lists it.',
  next_record_other_wallet: 'The QNet extension on this computer holds another wallet. Open it with this wallet, then choose Record on the network.',
  next_link_title: 'Next: link your phone or tablet',
  next_link_lead: 'Your node is recorded. It runs on a phone or tablet, in QNet Wallet, with this same wallet:',
  next_link_1: 'Install QNet Wallet on your phone or tablet. The Wallet page says where to get it.',
  next_link_2: 'Open it, tap "Import Existing Wallet" and type this wallet\'s recovery phrase: the same words give the same wallet.',
  next_link_3_qr: 'Link the phone: press "Link a device" and confirm in QNet Wallet (on a computer, scan the QR code with the phone\'s camera). Or in QNet Wallet open the "Node" tab and tap "Use this device".',
  next_link_3_app: 'Link the phone: in QNet Wallet open the "Node" tab and tap "Use this device".',
  next_link_done: 'Once the phone answers the network, this page shows the node as running.',
  next_running: 'Your node runs while QNet Wallet runs on that device: open, in the background or behind the lock screen, and online.',
  next_offline: 'The linked device has not answered the network lately. Open QNet Wallet on it, or press I\'m back on the Overview.',
  next_device_pending: 'A new device is linked. Waiting for its first answer; this page moves on by itself.',
  next_super: 'This wallet\'s activation is for a super node, which runs on a server. Its code and the server\'s settings are on the Overview.',
  next_resume: 'An activation started in this browser is not finished. Its payment address and key are here, and it goes on from where it stopped.',
  no_node_super_where: 'Super: activated only in the QNet extension on a computer; it runs on your own server.',
  next_open_overview: 'Open the Overview',

  // Where the wallet's activation stands, from every source (src/lib/cabinet/wallet-activation.ts)
  state_loading: 'Checking this wallet…',
  state_locked: 'The QNet extension is locked. Unlock it to see this wallet\'s activation; nothing is offered until then.',
  state_not_connected: 'The QNet extension has not approved this site for this wallet. Connect it again to see this wallet\'s activation; nothing is offered until then.',
  state_unknown: 'Nothing can be burned for this wallet until every check answers.',
  state_retry_note: 'This page tries again by itself every half minute.',
  check_network: 'The QNet network did not answer whether this wallet has a node.',
  check_server: 'The site\'s record of activations did not answer.',
  check_extension: 'The QNet extension that holds this wallet did not answer.',
  check_solana: 'The search of this wallet\'s Solana history did not finish. The QNet extension with this wallet searches it to the end with "Recover my code".',
  state_update_extension: 'Update the QNet extension: this version cannot show the site this wallet\'s activation.',
  state_reserved: 'An activation of this wallet is starting in another browser or on another device. Nothing more is offered here until {time}.',
  state_reserved_here: 'An activation of this wallet started in this browser. It goes on in the Activate tab.',
  state_sending: 'A burn for this wallet is on its way to Solana. Its code appears here once it is final.',
  state_unusable: 'This wallet already burned 1DEV for a node in a form no Light or Super activation code comes from. That burn is its one activation, so nothing more is offered for it. To activate a node, press Disconnect and connect another wallet.',
  one_code: 'One wallet, one code: a light node or a super node, chosen once.',
  burned_title: 'Your activation code',
  burned_light_lead: 'This wallet\'s light node activation. The code is only a receipt: keep it, you never need to type it.',
  burned_payment_lead: 'The burn for this wallet\'s light node is final, and the code above is its receipt. Register the node with QNet Wallet, in this browser or any other where this wallet is connected.',
  super_code_lead: 'This wallet\'s super node activation. The server needs the code, the burn and its amount below.',
  super_steps_title: 'Run the server',
  super_step_server: 'Take a Linux server with a public IP address that runs around the clock, install Docker, and open TCP ports 8001, 9876 and 9877 and UDP port 10876:',
  super_step_build: 'Get the QNet node software and build it:',
  super_step_seed: 'On the server only, put this wallet\'s recovery phrase in a file only you can read:',
  super_step_start: 'Start the node with these settings:',
  super_step_check: 'Check that it runs: it answers ok with a height that grows.',
  super_step_joined: 'The Overview shows the node once its server joins the network.',
  super_title: 'Your super node',
  super_id: 'Super node ID',
  super_last_seen: 'Last seen: {time}',
  super_last_seen_unknown: 'Last seen: not known yet',
  super_heartbeats: 'Heartbeats this epoch: {current} of {required} needed',
  super_heartbeats_unknown: 'Heartbeats this epoch: not known yet',
  super_barred: 'The network bars this node: its reputation is below the network\'s floor, so its epochs are not counted.',
  super_epochs: 'Epochs counted: {counted} · missed: {missed}, of the {total} the network settled lately',
  super_move: 'Move it to the wallet in QNet Wallet\'s Node tab.',
  super_online_note: 'The server answers the network.',
  super_offline_note: 'The network has not heard from the server lately. Check that the node software runs on it.',
  super_status_checking: 'Reading the super node\'s status…',
  super_device: 'A super node runs on its server; there is no device to link.',
  super_note: 'A super node is activated only in the QNet browser extension on a computer, with this same wallet; its server then runs with the same recovery phrase. A phone or the one-time payment address activates light nodes only.',
  super_note_install: 'Get the extension',
  super_note_guide: 'Show the super node guide',

  // A QNet Link request
  link_preparing: 'Preparing the request…',
  link_open_app: 'Open QNet Wallet',
  link_open_note: 'QNet Wallet shows the request before anything happens. Come back to this page when it is done.',
  link_open_here: 'Open QNet Wallet on this device',
  link_qr_label: 'QR code of this request for QNet Wallet',
  link_scan: 'Scan it with the camera of the phone or tablet that holds QNet Wallet.',
  link_qr_private: 'The code is for your own device. Do not share it or show it to anyone.',
  link_waiting: 'Waiting for QNet Wallet · expires in {time}',
  link_busy: 'The site is busy. Try again in a minute.',
  link_network: 'The site could not be reached. Check the connection and try again.',
  link_refused: 'The site refused the request. Reload the page and try again.',
  link_expired: 'The request expired after ten minutes. Ask again: nothing was lost.',
  link_unreadable: 'The answer could not be read, so nothing is shown. Start again; QNet Wallet itself shows what it did.',
  link_insecure: 'This page needs a secure (https) connection to make the request.',
  link_rate_limited: 'Too many requests from this network. Try again in {minutes} min.',
  link_answer_rejected: 'The answer says the request was declined in QNet Wallet.',
  link_answer_no_wallet: 'The answer says QNet Wallet holds no wallet yet.',
  link_answer_internal: 'The answer says QNet Wallet could not complete the request.',
  link_not_opened: 'QNet Wallet did not open. If this page is inside another app, open it in the device\'s own browser, or show the QR code for another device.',
  cancel: 'Cancel',
  start_again: 'Start again',
  link_ask_again: 'Ask again',
  try_again: 'Try again',

  // Node status
  checking: 'Checking the QNet network…',
  unreachable: 'The QNet network could not be reached.',
  no_node: 'This wallet has no node.',
  registration_pending: 'The QNet network is recording the registration. This usually takes one to three minutes; this page then moves on by itself.',
  no_device: 'The node does not run on any device now.',
  device_state_online: 'The device answers the network.',
  device_state_offline: 'The device has not answered the network lately.',
  device_state_pending: 'A new device is linked. Waiting for its first answer.',
  badge_online: 'Online',
  badge_offline: 'Offline',
  badge_waiting: 'Waiting',
  answered_yes: 'Answered this epoch: Yes',
  answered_no: 'Answered this epoch: Not yet',
  counted: 'Counted epochs: {counted} of the last {total}',
  balance: 'Node balance: {amount} QNC',
  balance_unknown: 'Node balance: could not be read',
  balance_min: 'The node balance can be moved to the wallet once it reaches 1 QNC.',
  action_move: 'Move to wallet',
  action_link_device: 'Link a device',

  // Device
  device_title: 'Device',
  devices_lead: 'One node runs on one phone or tablet at a time.',
  devices_link_lead: 'Open the request in QNet Wallet with this wallet, on the phone or tablet that should run the node. That device confirms it and runs the node from then on.',
  devices_link_closed: 'Linking a device from this page opens soon. Meanwhile, open QNet Wallet on the phone with this wallet: Node tab, Use this device.',
  devices_linked_answer: 'The answer says the device that opened the request runs the node now. The rows above follow the QNet network.',
  devices_check: 'The check number of this request is {number}. If QNet Wallet shows another number, another device answered: link again from the device you hold.',
  devices_last_counted: 'Last counted answer: epoch {epoch}',
  devices_not_counted: 'Last counted answer: none in the recent epochs',
  device_platform_android: 'Android',
  device_platform_ios: 'iPhone or iPad',
  device_platform_unknown: 'Unknown device',
  device_platform_ios_short: 'iOS',
  device_model_platform: '{model} · {platform}',
  device_linked_since: 'Linked since {day}',
  device_last_answer: 'Last answer: epoch {epoch}',
  device_no_answer: 'No answer yet',
  device_wake_overview: 'Wake it from Overview',
  devices_move_title: 'Move the node to another device',
  devices_move_lead: 'Open the request in QNet Wallet with this wallet, on the phone or tablet that should run the node. That device takes over, and the one before it stops.',

  // The latest epoch not counted (src/lib/cabinet/last-miss.ts): what happened, then what to do
  miss_woken: 'Epoch {epoch} was not counted: the network sent the device a wake, and no answer came before that epoch\'s check closed.',
  miss_late: 'Epoch {epoch} was not counted: the device answered after that epoch\'s check had closed.',
  miss_refused: 'Epoch {epoch} was not counted: the device answered, but the network did not accept the answer.',
  miss_not_delivered: 'Epoch {epoch} was not counted: the wake the network sent never reached the device. The push service or the device held it.',
  miss_no_push: 'Epoch {epoch} was not counted: the network has no way to wake the device yet, and the device did not ask for the check by itself.',
  miss_inactive: 'Epoch {epoch} was not counted: the device had not answered in the two epochs before it, so the network stopped waking it.',
  miss_not_sent: 'Epoch {epoch} was not counted: the network did not get its wake out to the device in that epoch.',
  miss_not_committed: 'Epoch {epoch} was not counted: the network published no check of this node\'s group in that epoch, so no node of the group was counted in it.',
  miss_todo_background_android: 'Let QNet Wallet run in the background on that device, set its battery use to Unrestricted and do not swipe it away.',
  miss_todo_background_ios: 'Let QNet Wallet run in the background on that device, keep Background App Refresh on for it and do not swipe it away.',
  miss_todo_background: 'Let QNet Wallet run in the background on that device, leave its battery use unrestricted and do not swipe it away.',
  miss_todo_open_or_wake: 'Open QNet Wallet on that device, or press I\'m back.',
  miss_todo_open_or_wake_overview: 'Open QNet Wallet on that device, or press I\'m back on the Overview.',
  miss_todo_open: 'Open QNet Wallet on that device.',
  miss_todo_open_once: 'Open QNet Wallet on that device once: it then tells the network how to wake it.',
  miss_todo_run_again: 'Open QNet Wallet on that device and run the node there again: Node tab, Use this device.',
  miss_todo_network: 'That was the network\'s miss: nothing needs changing on that device or in QNet Wallet.',
  // Whether the network's wake reached the device, by the device's own account
  delivery_reached: 'The wake reached the device.',
  delivery_not_reached: 'The wake did not reach the device.',

  // Unlink this device
  unlink_title: 'Unlink this device',
  unlink_lead: 'The node stops running on the linked phone or tablet. QNet Wallet on that device confirms it, and the device itself signs the change for the network: this page cannot unlink anything alone. The node stays with this wallet, its balance stays yours to move, and a device can be linked again at any time.',
  unlink_button: 'Unlink this device',
  unlink_lost: 'Lost the device, or QNet Wallet no longer opens on it? Move the node to another device below: the new device takes over and the old one stops.',
  unlink_title_wallet: 'Unlink the device',
  unlink_lead_wallet: 'The node stops running on the device it runs on now. The node and its balance stay with this wallet, and it can run on any device later. The wallet signs the change: this page cannot unlink anything alone.',
  unlink_lost_wallet: 'Lost the device, or QNet Wallet no longer opens on it? Unlink it here, from any device that has this wallet.',
  unlink_with_extension: 'Unlink with the extension',
  unlink_extension_note: 'The extension shows the linked device and asks you to confirm.',
  unlink_app_note: 'QNet Wallet with this wallet, on any device, shows the linked device and asks you to confirm.',
  unlink_error_NOT_LINKED: 'The answer says no device runs this wallet\'s node now.',
  unlink_error_NETWORK: 'The wallet could not reach the QNet network. Nothing changed; try again.',
  unlink_error_UNLINK_REFUSED: 'The QNet network did not take the unlink. Nothing changed; try again.',
  unlink_closed: 'Unlinking a device from this page opens soon. Meanwhile, the node leaves a device when another device takes it over, or when this wallet is deleted in QNet Wallet on that device.',
  unlink_failure_other_wallet: 'The extension holds another wallet than the one this page shows. Nothing was unlinked.',
  unlink_failure_timeout: 'The page stopped waiting for the extension. The device rows above show whether the device is unlinked.',
  unlink_failure_failed: 'The extension did not complete the request. The device rows above show whether the device is unlinked.',
  unlink_failure_unverifiable: 'The extension answered with data that could not be verified, so nothing is shown. The device rows above show whether the device is unlinked.',
  unlink_answer_ok: 'The answer says the device is unlinked, and the network took the change. The rows above follow the QNet network.',
  unlink_answer_unconfirmed: 'QNet Wallet stopped the node on that device, but the network did not confirm the change. Until another device is linked, it may still show a device linked.',

  // I'm back
  wake_lead: 'The device was off or offline? Ask the network to wake it now.',
  wake_button: 'I\'m back',
  wake_waiting: 'The network asked the linked device to answer. Waiting for its answer…',
  wake_answered: 'The linked device answered. Counted this epoch.',
  wake_no_answer: 'No answer yet. Open QNet Wallet on the linked device: a device does not wake an app that was closed from the app switcher.',
  wake_already: 'The node already answered this epoch.',
  wake_no_device: 'No device answers for this node.',
  wake_cooldown: 'The network cannot wake the device right now. Try again in a few minutes.',
  wake_cooldown_in: 'The network cannot wake the device right now. Try again in {minutes} min.',

  // Node balance
  claim_title: 'Node balance',
  claim_lead: 'Each counted epoch adds QNC to the node balance, which the QNet network keeps for this wallet. From 1 QNC, move it into the wallet: the wallet signs the move, and this page only asks.',
  claim_with_extension: 'Move to wallet with the extension',
  claim_extension_note: 'The extension shows the amount before it moves anything.',
  claim_with_app: 'Move with QNet Wallet',
  claim_app_note: 'QNet Wallet shows the amount and moves it once you confirm.',
  claim_closed: 'Moving the node balance from this page with QNet Wallet opens soon. QNet Wallet moves it from its Node tab.',
  claim_ok: 'The answer says {amount} QNC moved to the wallet. It is credited once a block includes it; the node balance above follows the QNet network.',
  claim_ok_part: 'The answer says {amount} QNC moved to the wallet, up to epoch {epoch}; the rest moves with the next request. It is credited once a block includes it.',
  claim_empty: 'The answer says the node balance is below 1 QNC, so nothing moved.',
  claim_error_NO_NODE: 'The answer says this wallet has no light node on the QNet network.',
  claim_error_NETWORK: 'The wallet could not reach the QNet network. Nothing moved; try again.',
  claim_error_CLAIM_REFUSED: 'The QNet network refused the move. Nothing moved; try again later.',
  claim_error_CLAIM_BUSY: 'A move of this node balance is already running. Wait for it to finish.',
  claim_failure_timeout: 'The page stopped waiting for the extension. The node balance above shows whether it moved.',
  claim_failure_failed: 'The extension did not complete the request. The node balance above shows whether it moved.',
  claim_failure_unverifiable: 'The extension answered with data that could not be verified, so nothing is shown. The node balance above shows whether it moved.',
  claim_failure_other_wallet: 'The extension holds another wallet than the one this page shows. Connect the extension\'s wallet on My node to move its node balance.',

  // History
  history_title: 'History',
  history_last_counted: 'Last counted epoch: {epoch}',
  history_never_counted: 'No epoch has been counted yet.',
  history_epochs: 'Epoch by epoch',
  history_recent: 'Recent epochs',
  history_see_all: 'See every epoch',
  history_col_epoch: 'Epoch',
  history_col_ended: 'Ended',
  history_col_result: 'Result',
  history_col_amount: 'Node balance added',
  history_col_moved: 'Moved to the wallet',
  history_counted: 'Counted',
  history_moved: 'Counted, moved to the wallet',
  history_missed: 'Missed',
  history_not_counted: 'Not counted',
  history_joined: 'Registered during this epoch',
  history_unchecked: 'Not checked by the network',
  history_unknown: 'Could not be read',
  history_empty: 'No epoch of this node has been settled yet.',
  history_unavailable: 'The history could not be read from the QNet network.',
  history_settled_note: 'An epoch shows here once the network has settled it, about 4 hours after it ends. Missed means the node did not answer the network enough during that epoch.',
  history_unchecked_note: 'Not checked by the network: that epoch the network published no check for this node\'s group, so the node is not blamed for it.',
  history_no_start: 'When this node was registered could not be read from the explorer, so epochs from before it may be listed too, as not counted.',
  history_no_archive: 'Dates and moves to the wallet could not be read from the explorer right now.',
  history_earlier: 'Earlier epochs moved to the wallet',
  history_earlier_note: 'For older epochs the explorer keeps only the ones moved to the wallet.',
  claim_epochs_title: 'Waiting to be moved',
  claim_epochs_note: 'The counted epochs that make up the node balance.',
  claim_epochs_none: 'No counted epoch is waiting to be moved.',

  // Copying
  copy: 'Copy',
  copied: 'Copied',
  copy_blocked: 'The browser blocked copying; select the text instead.',

  // Activation
  activate_title: 'Activate a node',
  act_lead: 'A light node, which runs in QNet Wallet on a phone or tablet. For a phone, or a computer without the QNet extension. Five steps:',
  act_way_1: 'QNet Wallet confirms the wallet the node is for.',
  act_way_2: 'This page makes a one-time payment address for that wallet.',
  act_way_3_testnet: 'You send test 1DEV and a little test SOL to it from your wallet; "Get test tokens" on the Testnet page puts them in your wallet free.',
  act_way_3_mainnet: 'You send the 1DEV and a little SOL to it from your wallet.',
  act_way_4: 'The page burns the 1DEV on Solana. From then on the burn is this wallet\'s activation, and its code shows at once.',
  act_way_5: 'QNet Wallet confirms again, and the page records your node on the QNet network. That step also works later, from any browser where this wallet is connected.',
  act_unsupported: 'This browser cannot keep a payment key safely. Update it or use another browser.',
  act_price: 'Activation: {price} 1DEV, burned on Solana. Nobody receives it. One wallet, one node: this light node or a super node made in the QNet extension, never both.',
  act_price_unavailable: 'The activation price could not be read from the QNet network.',
  act_no_burn_phase: 'The QNet network does not activate light nodes with a 1DEV burn now.',
  act_start: 'Make a payment address',
  act_start_failed: 'The payment address could not be kept in this browser. Check that the browser allows this site to store data, then try again.',
  act_reserve_title: 'Confirm in QNet Wallet',
  act_reserve_lead: 'QNet Wallet confirms that this light node is for wallet {wallet}: it shows "Set up a light node for this wallet". Nothing leaves the wallet. The payment address appears here once it is confirmed.',
  act_reserve_rejected: 'QNet Wallet declined. No payment address was made.',
  act_reserve_other_wallet: 'QNet Wallet answered for another wallet than the one connected here. No payment address was made.',
  act_reserve_stale: 'aiqnet.io did not take the confirmation from QNet Wallet: its time is more than a day old, or ahead of the clock of aiqnet.io. Check the date and time of the device with QNet Wallet, confirm again in QNet Wallet, then burn. Nothing was burned.',
  act_resume: 'An activation started in this browser is not finished. It continues here.',
  act_discard: 'Cancel this activation',
  act_address_title: 'Payment address',
  act_address_note: 'Send only to this address. The page burns exactly the activation amount from it, nothing else; aiqnet.io never holds its key.',
  act_owner: 'The node is registered to your QNet wallet {wallet}; this one-time address only burns the 1DEV. Its key stays in this browser until what is left has gone back.',
  act_keep_browser: 'Keep this browser until the burn: if nothing is burned within 24 hours, the page sends what arrived back to the wallet and deletes the payment address (test tokens go back only when the page knows the wallet\'s Solana address). After the burn this browser keeps the payment address only to send back what is left; the registration can be finished in any browser. A browser may delete this site\'s data after about a week without a visit, and what is left would then stay on the address: finish soon.',
  act_address_qr: 'QR code of the payment address',
  act_mainnet_send: 'Send {price} 1DEV and {sol} SOL to this address from your wallet.',
  act_testnet_send: 'Send {price} test 1DEV and {sol} test SOL (Solana devnet) to this address from your wallet.',
  act_request_qr: 'Payment request of {price} 1DEV to the payment address',
  act_request_note: 'Scan the code with QNet Wallet: it fills in the address, 1DEV and the amount.',
  act_request_note_phone: 'On this phone, copy the address, then in QNet Wallet send {price} 1DEV and, separately, {sol} SOL to it. From another device, scan the codes instead.',
  act_copy_request: 'Copy payment request',
  act_sol_line: 'The {sol} SOL pays the burn\'s network fee and the address\'s rent: scan this second code for it, or send it to the same address.',
  act_sol_qr: 'Payment request of {sol} SOL to the payment address',
  act_no_tokens: 'No test tokens yet? {link}',
  act_no_tokens_link: 'Get them to your wallet',
  act_received: 'Received: {oneDev} of {price} 1DEV · {sol} of {solNeed} SOL',
  act_burn_lead: 'Burn {price} 1DEV from the payment address. The tokens are destroyed on Solana; nobody receives them. This cannot be undone.',
  act_burn: 'Burn',
  act_burn_busy: 'This activation continues in another tab of this browser.',
  act_burn_refused: 'Solana did not take the burn. Nothing was burned; try again.',
  act_burn_unavailable: 'Solana could not be reached. Nothing was burned; try again.',
  act_price_changed: 'The network now asks another amount for an activation. Nothing was burned: check the new amount, then press Burn again.',
  act_wallet_has_node: 'The chosen wallet already has a node, or one being recorded. One wallet, one node of either type: to activate another one, press Disconnect and connect another wallet.',
  act_has_activation: 'This wallet has its activation already, so nothing more is burned for it. Its code and the next step are on the Overview.',
  act_no_wallet: 'Connect the wallet the node is for first: its burn is reserved for that wallet alone.',
  act_reconfirm: 'QNet Wallet confirms this wallet once more before the burn. Nothing was burned.',
  act_reserved: 'An activation of this wallet runs in another browser or on another device, or its burn is still on its way. Nothing was burned here; try again once it has ended.',
  act_payment_not_open: 'Activation from a payment address is not open yet: the QNet network takes it once its next update is active. No address is made and nothing can be burned here until then.',
  act_check_unavailable: 'A check of this wallet did not answer (the QNet network, the site\'s record or the wallet\'s Solana history). Nothing was burned; try again.',
  act_reservation: 'The reservation of this wallet ended before the burn was sent. Nothing was burned; press Burn again.',
  act_burning: 'Sent. Waiting for Solana to finalize… (up to 90 s)',
  act_burn_unknown: 'The burn may still land. This page keeps checking; do not send another.',
  act_burn_checking: 'An earlier burn of this activation may still land. This page keeps checking it for a few minutes; nothing new was burned. Try again then.',
  act_burn_failed: 'The burn failed on Solana. No tokens were burned.',
  act_try_again: 'Try again',
  act_receipt_title: 'Receipt',
  act_burned: 'Burned {amount} 1DEV',
  act_burn_tx: 'Burn transaction',
  act_code: 'Activation code',
  act_code_note: 'Keep the code: it identifies this activation. The network does not need it.',
  act_link_title: 'QNet Wallet',
  act_link_lead: 'QNet Wallet shows the request, gives its wallet\'s consent to register a light node with this burn, and runs the node on that device. One confirmation.',
  act_link_open: 'Continue in QNet Wallet',
  act_link_show_qr: 'Show the QR code',
  act_link_named: 'The request is for wallet {wallet}.',
  act_answer_for: 'QNet Wallet answered for node {node} of wallet {wallet}.',
  act_check: 'This page shows the check number {number}. Does QNet Wallet show the same number?',
  act_check_yes: 'It matches, register',
  act_check_no: 'It does not match',
  act_checking_node: 'Checking the QNet network before the registration…',
  act_mismatch: 'QNet Wallet answered for another wallet. Do not continue: this burn is for {wallet} only. Start a new request from that wallet.',
  act_stale: 'The consent from QNet Wallet is too old for the QNet network. Ask QNet Wallet again: the burn and its code stay.',
  act_ask_again: 'Ask QNet Wallet again',
  act_node_exists: 'This wallet already has a node on the QNet network. One wallet, one node: nothing more is registered for it.',
  act_linked_answer: 'This wallet\'s light node is already on the QNet network and now runs on that device.',
  act_relink: 'Start a new request',
  act_recording: 'Recording the registration on the QNet network… usually one to three minutes.',
  act_bind_v2_pending: 'The QNet network takes this registration only once its next update is active. The burn stays this wallet\'s: the registration goes through after that update, and nothing is burned again.',
  act_refused: 'The QNet network did not accept the registration ({code}).',
  act_refused_wallet_has_node: 'The QNet network refused the registration: this wallet already has a node (one wallet, one node).',
  act_done: 'Registered on the QNet network.',
  act_done_device: 'The node runs on the device that gave the consent once the QNet network records it. If QNet Wallet showed "This device can\'t run a node.", link another phone or tablet from My node.',
  act_go_cabinet: 'Open My node',
  act_leftovers: '{oneDev} 1DEV and {sol} SOL are left on the payment address.',
  act_refund_label: 'Solana address',
  act_refund_send: 'Send what is left',
  act_refund_invalid: 'This is not a Solana address.',
  act_refund_failed: 'What is left could not be sent. Try again.',
  act_refund_short: 'The payment address has too little SOL to pay the network fee for sending them back. Send {sol} SOL more to it from any wallet or exchange; the page then sends everything back.',
  act_refund_short_testnet: 'The payment address has too little test SOL to pay the network fee for sending them back. Send {sol} test SOL more to it from your wallet (the Testnet page\'s faucet gives test SOL); the page then sends everything back.',
  act_refund_leave: 'Leave it',
  act_refund_leave_warn: 'The {oneDev} 1DEV and {sol} SOL stay on the payment address for good: once the page deletes its key, nobody can move them. Delete the key anyway?',
  act_delete_key: 'Delete the key',
  act_refund_to: 'Sending them back to the wallet\'s Solana address:',
  act_refund_ask: 'They go back to the wallet: ask QNet Wallet on this device for its Solana address, or enter the Solana address they should go to.',
  act_refund_enter: 'They go back to the wallet: enter the Solana address they should go to.',
  act_refund_other_wallet: 'QNet Wallet shared the addresses of another wallet than the one this burn is for. Ask again from that wallet, or enter a Solana address.',
  act_expired: 'Nothing was burned within 24 hours, so this activation ends here.',
  act_closing_empty: 'Nothing is on the payment address. If a transfer to it is still on its way, keep this page: the page sends it back to the wallet once it arrives.',
  act_closing_delete: 'Delete the payment address',
  act_closing_delete_warn: 'Anything sent to the payment address after the page deletes its key is lost for good. Delete the key anyway?',
  act_leftovers_now: 'Send what is left back now',
  act_leftovers_now_note: 'The burn stays this wallet\'s activation: finish the registration later in any browser where this wallet is connected. What is left goes back to the wallet now, and the page deletes the payment key.',
  act_other_burn: 'This wallet\'s activation is another burn (the network registered its node with it, or it is on the site\'s record), so this burn registers no node.',
  act_closed: 'The activation ended and its payment address is deleted. To start again, make a new payment address.',
  act_closed_has_node: 'The activation ended and its payment address is deleted. This wallet already has a node or an activation, so it needs no new payment address.',
  act_returned: 'What was left went back and the payment address is deleted. The burn stays this wallet\'s activation: its code and the next step are on the Overview.',
  act_payment_title: 'Light node: pay with a one-time address',
  act_super_title: 'Super node: only in the QNet extension',
  act_phone_closed: 'Activation from this page with QNet Wallet opens soon. On a computer, the QNet extension activates a light node now.',
  act_get_extension: 'To activate from this computer with the QNet browser extension, get the extension, then reload this page.',
  act_get_extension_link: 'Get the extension',
  act_extension_other_wallet: 'The QNet extension on this computer holds another wallet than the one shown here, so it activates nothing for this one. To use the extension, open it with this wallet and connect it on My node.',

  // Activation with the QNet extension (a computer)
  ext_title: 'With the QNet extension',
  ext_lead: 'The QNet extension on this computer burns the activation amount from its own Solana address and, for a light node, records the node on the QNet network in the same approval.',
  ext_type_label: 'Node type',
  ext_type_light: 'Light node',
  ext_type_light_where: 'Runs on a phone or tablet, in QNet Wallet.',
  ext_type_super: 'Super node',
  ext_type_super_where: 'Runs on a server with the QNet node software.',
  ext_price: 'Burns {price} 1DEV',
  ext_price_loading: 'Reading the price…',
  ext_price_unavailable: 'Price unavailable',
  ext_price_phase2: 'Phase 2: no 1DEV burn',
  ext_price_missing: 'The network\'s price could not be read. The extension shows the price itself before anything is burned.',
  ext_phase2: 'The network reports phase 2: burning 1DEV no longer activates a node, so there is nothing to confirm here.',
  ext_start: 'Activate with the extension',
  ext_start_note: 'The extension shows the price and asks you to confirm before anything is burned.',
  ext_fact_destroyed: 'Burned 1DEV is destroyed on Solana: nobody receives it, and a burn cannot be undone.',
  ext_fact_one: 'One wallet, one code: a light node or a super node, chosen once. A wallet that already has its activation gets its code back, and nothing is burned.',
  ext_fact_recover: 'The extension keeps showing the code on its Activate tab.',
  ext_other_origin: 'Node activation with the QNet extension runs on aiqnet.io.',
  ext_heading_ok: 'Activation code issued',
  ext_heading_exists: 'This wallet already has an activation',
  ext_heading_superseded: 'An older burn is this wallet\'s activation',
  ext_heading_pending: 'Burn sent, not final yet',
  ext_heading_rejected: 'Declined',
  ext_heading_error: 'Not done',
  ext_lead_ok: 'The wallet burned {amount} 1DEV and derived the node\'s activation code.',
  ext_lead_exists: 'Nothing was burned. A wallet has one activation, and this is its code.',
  ext_lead_superseded: 'A burn of this wallet went through and its 1DEV are destroyed, but an older burn of the wallet, made on another device, is its one activation. The code is that older burn\'s; the newer burn gives none.',
  ext_lead_pending: 'There is no code yet. Once the burn is final on Solana, the extension shows the code on its Activate tab.',
  ext_lead_rejected: 'The request was declined in the extension. Nothing was burned and nothing was shared.',
  ext_other_type: 'It is for a {got}, not the {chosen} chosen here.',
  ext_field_type: 'Node type',
  ext_field_code: 'Activation code',
  ext_field_burn: 'Burn',
  ext_field_superseded: 'Also burned, no code',
  ext_field_qnet: 'QNet address',
  ext_field_solana: 'Solana address',
  ext_amount: '{amount} 1DEV',
  ext_footer: 'As reported by the extension.',
  ext_footer_code: 'As reported by the extension. The code matches the burn data it came with.',
  ext_in_flight: 'The extension may still be sending this wallet\'s burn. Do not start another activation of this wallet until the burn is final on Solana; the extension then shows the code on its Activate tab.',
  ext_next: 'Next',
  ext_light_registered: 'Registered on the QNet network.',
  ext_show_wallet: 'Show this wallet\'s node',
  ext_super_seed: 'Enter the recovery phrase only in the file that QNET_WALLET_SEED_FILE names, on your server, never on a website. Every setting of the node is in',
  ext_super_running: 'Running a node',
  ext_super_spelling: 'Write the phrase as its words in lowercase, on one line, separated by single spaces. The node uses the text as written and does not check it: capitals, a line break or a typo give another wallet, which does not match this burn.',
  ext_error_PRICE_UNAVAILABLE: 'The wallet could not read the activation price from the network. Nothing was burned.',
  ext_error_PHASE_UNSUPPORTED: 'The network reports phase 2, where burning 1DEV no longer activates a node. Nothing was burned.',
  ext_error_PRICE_CHANGED: 'The price changed after it was confirmed. Nothing was burned. Start again to see the new price.',
  ext_error_INSUFFICIENT_SOL: 'The wallet does not have enough SOL for the Solana fee. Nothing was burned.',
  ext_error_INSUFFICIENT_TOKENS: 'The wallet does not have enough 1DEV. Nothing was burned.',
  ext_error_SIMULATION_FAILED: 'The burn failed its Solana simulation and was not sent. Nothing was burned.',
  ext_error_TX_FAILED: 'The burn was sent and failed on Solana. No tokens were burned.',
  ext_error_SOLANA_UNAVAILABLE: 'The wallet could not reach Solana. Nothing was burned.',
  ext_error_HISTORY_TOO_LONG: 'The wallet reached Solana, but this wallet\'s history there is too long to search in one go, so the search stopped before the end. Nothing was burned. The wallet keeps what it checked: start again to continue the search.',
  ext_error_NODE_EXISTS: 'This QNet wallet already has a node or an activation: its code and the next step are on the Overview. Nothing was burned.',
  ext_error_BURN_UNUSABLE: 'This wallet already burned 1DEV for a node in a form no Light or Super activation code comes from (a Full node of an earlier version, or a burn from another of its 1DEV token accounts). The network counts that burn as the wallet\'s one activation. Nothing was burned. Do not start another activation of this wallet.',
  ext_error_BURN_IN_PROGRESS: 'Another activation of this wallet is running, in this browser or another one, or on another device. Wait for it to finish.',
  ext_error_NO_WALLET: 'The extension has no wallet yet. Create or import one in the extension, then start again.',
  ext_error_INTERNAL: 'The wallet could not complete the request.',
  ext_failure_rejected: 'The request was declined in the extension.',
  ext_failure_cooldown: 'Too many declined requests. Try again in a few minutes.',
  ext_failure_unauthorized: 'The extension does not allow this request from this page.',
  ext_failure_unsupported: 'This version of the QNet extension cannot do this. Update the QNet extension, reload this page and try again.',
  ext_failure_disconnected: 'The extension is disconnected. Reload the page and try again.',
  ext_failure_timeout: 'The page stopped waiting for the extension. If you confirmed a burn, the extension shows the result in its Activate tab.',
  ext_failure_failed: 'The extension did not complete the request. If you confirmed a burn, the extension shows the result in its Activate tab.',
  ext_failure_unverifiable: 'The extension answered with data that could not be verified, so nothing is shown. Its Activate tab shows what it did.',
  link_error_NO_WALLET: 'QNet Wallet holds no wallet yet.',
  link_error_WALLET_MISMATCH: 'QNet Wallet holds no wallet that matches the one this request names.',
  link_error_NO_NODE: 'QNet Wallet found no light node of this wallet on the QNet network.',
  link_error_NODE_OTHER: 'This wallet has a server node, or aiqnet.io records a super node activation for it; a light node cannot be added to it.',
  link_error_NETWORK: 'QNet Wallet could not reach the QNet network. Try again.',
  link_error_BIND_REFUSED: 'The QNet network did not take the device link. Nothing was done. If QNet Wallet shows "This device can\'t run a node.", link another phone or tablet; otherwise try again.',
  link_error_NOT_LINKED: 'QNet Wallet found no device that runs this wallet\'s node.',
  link_error_UNLINK_REFUSED: 'The QNet network did not take the unlink. Nothing changed; try again.',
  link_error_INTERNAL: 'QNet Wallet could not complete the request.',

  // Node details (the Overview): the activation behind the node
  details_title: 'Node details',
  details_note: 'The activation code is only a receipt of the burn: it authorizes nothing, and you never need to type it.',
  details_note_super: 'The server needs this code, with the burn and its amount: they are in its settings below.',
  code_field_status: 'On the QNet network',
  code_status_recorded: 'Recorded',
  code_status_recorded_at: 'Recorded at block {height}',
  code_status_pending: 'Being recorded now',
  code_status_not_yet: 'Not recorded yet',
  code_field_node: 'Light node ID',
  code_field_amount: 'Amount burned',
  code_source_network: 'From the QNet network\'s record of the registration.',
  code_source_extension: 'As the QNet extension that holds this wallet reports it.',
  code_source_browser: 'From the activation made in this browser.',
  code_source_record: 'From the site\'s record of this wallet\'s activation.',
  code_source_scan: 'From the burn on this wallet\'s own Solana address.',
  code_source_kept: 'As the QNet extension reported it in this browser.',
  code_code_later: 'The code follows once the burn is final on Solana.',
  code_continue: 'Continue the activation',
  code_no_registration: 'No light node is registered to this wallet on the QNet network yet. If the QNet extension burned for it, open the extension and choose Record on the network.',
  code_not_archived: 'This wallet\'s light node is registered, but the burn details of its registration are not kept here, so its code cannot be shown. The wallet that burned for it shows the code.',
  code_archive_unavailable: 'The burn details of this registration could not be read from the explorer right now. Reload the page to try again.',

  // How it works (/docs/how-it-works): every step of the three ways, in the words the app, the extension and this site
  // show. A "quoted" label is checked against those words (cabinet-guide.test.mjs).
  guide_title: 'How it works',
  guide_lead: 'Three ways to a running node: a light node from a phone or from a computer, and a super node, which is activated only in the QNet extension on a computer and runs on your server. One wallet has one node. Choose yours and follow every step in order.',
  guide_path_label: 'Choose your way',
  guide_path_phone: 'Phone only',
  guide_path_computer: 'From a computer',
  guide_path_super: 'Super node',
  guide_phone_intro: 'Everything on one phone or tablet, with QNet Wallet.',
  guide_computer_intro: 'Pay with the QNet extension on a computer. The node then runs on your phone.',
  guide_super_intro: 'A super node is activated only in the QNet extension on a computer, never from a phone or with a payment address. It then runs on your own server, with the same wallet.',
  guide_phone_install: 'Install QNet Wallet on your phone or tablet; the Wallet page says where to get it. Open it and tap "Create New Wallet" or "Import Existing Wallet". To import, type your 12 words, tick "I accept the Terms of Service", tap "Import Wallet" and go on at step 5.',
  guide_phone_protect: 'Tick "I accept the Terms of Service" and tap "Create Wallet". The app locks the wallet with your phone\'s screen lock; only a phone without one first asks for a password of at least 8 characters, twice.',
  guide_phone_words: 'Write the 12 words on paper, in order, and keep the paper somewhere safe: whoever has these words owns the wallet. Then tap "I Wrote It Down".',
  guide_phone_words_check: 'The app asks for 3 of the words. Pick each one, then tap "Confirm & Create Wallet". Your wallet is ready.',
  guide_phone_open_site: 'On the same phone, open its own web browser, not the Browser tab inside QNet Wallet, and go to aiqnet.io/node.',
  guide_phone_connect: 'Tap "QNet Wallet on this phone", then "Open QNet Wallet".',
  guide_phone_share: 'QNet Wallet opens and shows "Share this wallet\'s addresses", a request through aiqnet.io. Tap "Confirm", then switch back to the browser: My node opens with your address.',
  guide_phone_start: 'My node opens the Activate tab. Tap "Make a payment address", then "Open QNet Wallet".',
  guide_phone_reserve: 'QNet Wallet shows "Set up a light node for this wallet", a request through aiqnet.io. Tap "Confirm", then switch back to the browser: the page shows the payment address and what to send to it.',
  guide_phone_fund_testnet: 'Tap "Get them to your wallet", then "Get test tokens" on the Testnet page: free test 1DEV and SOL arrive in your wallet. Go back to the Activate tab, tap "Copy" under the payment address, and in QNet Wallet send it the 1DEV amount, then the SOL amount the page shows. Wait until the page shows both arrived.',
  guide_phone_fund_mainnet: 'Tap "Copy" under the payment address, then in QNet Wallet send it the 1DEV amount, then the SOL amount the page shows. Wait until the page shows both arrived.',
  guide_phone_burn: 'Tap "Burn". The 1DEV are destroyed on Solana and nobody receives them; this cannot be undone. Wait up to 90 seconds: the page shows your activation code, a receipt you never need to type.',
  guide_phone_link: 'Tap "Continue in QNet Wallet", then "Open QNet Wallet". QNet Wallet shows "Link this wallet\'s node to this device": tap "Confirm", then switch back to the browser.',
  guide_phone_done: 'Wait one to three minutes until the page says "Registered on the QNet network.", then tap "Open My node".',
  guide_phone_move: 'The network checks your node once every epoch, about 4 hours, and its balance grows. From 1 QNC, open the "Node" tab in QNet Wallet and tap "Move to wallet".',
  guide_or_move_site: 'Or on My node: "Move with QNet Wallet", then "Open QNet Wallet" and "Confirm".',
  guide_or_move_app: 'Or in QNet Wallet itself: "Node" tab, "Move to wallet".',
  guide_link_wallet: 'Open the Wallet page',
  guide_link_faucet: 'Open the test token faucet',
  guide_phone_closed: 'Paying from a phone opens here soon. Today a light node is activated from a computer with the QNet extension, and then runs on your phone.',
  guide_show_computer: 'Show the computer guide',
  guide_pc_install: 'On your computer, install the QNet Wallet extension (the Wallet page links it) and pin it to the browser\'s toolbar, so its icon stays in sight.',
  guide_pc_setup: 'Click the QNet icon, then "Create or import a wallet": a setup tab opens. Choose "Create a new wallet", or "Import a wallet" to type 12 words you already have, click "Continue" and go on at step 5.',
  guide_pc_words: 'Click "Show the words", write the 12 words on paper in order, tick "I wrote the words down on paper, in order." and click "Continue".',
  guide_pc_check: 'Type the 3 words it asks for from your paper and click "Check".',
  guide_pc_password: 'Choose a password of at least 8 characters, type it twice and click "Create wallet" ("Import wallet" after an import), then "Done".',
  guide_pc_solana: 'Click the QNet icon again, switch the top to "Solana", open "Receive" and click "Copy address".',
  guide_pc_tokens_testnet: 'Open aiqnet.io/testnet, paste the address into the faucet and click "Get test tokens". You get free test 1DEV and a little SOL; they have no value.',
  guide_pc_tokens_mainnet: 'Send the activation price in 1DEV, and a little SOL for the network fee, to that Solana address from any wallet or exchange.',
  guide_pc_connect: 'Open aiqnet.io/node and click "QNet extension on this computer". In the extension window "Connect this site?" click "Connect".',
  guide_pc_activate: 'My node opens the Activate tab. Keep "Light node" selected and click "Activate with the extension".',
  guide_pc_burn: 'In the extension window "Activate a Light node?" tick the box and click "Burn … 1DEV" (a locked extension first asks for its password to unlock). Wait up to two minutes: the extension burns, records the node on the network, and the page shows your activation code, which is only a receipt.',
  guide_pc_phone: 'On your phone, install QNet Wallet and tap "Import Existing Wallet". If it asks for a password, type one of at least 8 characters twice and tap "Next". Type the same 12 words, tick "I accept the Terms of Service" and tap "Import Wallet".',
  guide_pc_link: 'Back on the computer, click "Link a device" on My node\'s Overview: a QR code appears. Scan it with the phone\'s camera. QNet Wallet opens and shows "Link this wallet\'s node to this device": tap "Confirm".',
  guide_pc_link_app: 'On the phone, open the "Node" tab in QNet Wallet and tap "Use this device", then "Use this device" again to confirm.',
  guide_or_use_device: 'Or on the phone: QNet Wallet, "Node" tab, "Use this device".',
  guide_pc_move: 'Each epoch, about 4 hours, the node balance grows. From 1 QNC, click "Move to wallet with the extension" on My node, then "Move to wallet" in the extension window.',
  guide_super_activate: 'My node opens the Activate tab. Choose "Super node" and click "Activate with the extension".',
  guide_super_burn: 'In the extension window tick the box and click "Burn … 1DEV" (a locked extension first asks for its password to unlock). Wait up to two minutes: the extension burns and the page shows your activation code.',
  guide_super_code: 'The page shows your activation code and every server step right away; later the Overview shows them in any browser where this wallet is connected.',
  guide_super_server: 'On a Linux server with a public IP address and Docker: open the ports, build the QNet node software, put this wallet\'s recovery phrase in a file and start the node with the code, the burn and its amount. The Overview lists every command; Running a node explains each setting.',
  guide_super_watch: 'The Overview shows the node once its server joins the network: online or not, when it was last seen, its heartbeats this epoch (an epoch is about 4 hours), its epochs and its node balance.',
  guide_super_move: 'Each epoch, about 4 hours, the node balance grows. From 1 QNC, move it into the wallet: install QNet Wallet on a phone, tap "Import Existing Wallet" and type the same 12 words, then tap "Move to wallet" on its "Node" tab.',
  guide_short_phone_1: 'Create or import a wallet in QNet Wallet.',
  guide_short_phone_2: 'Open aiqnet.io/node on the phone and connect.',
  guide_short_phone_3: 'Activate: confirm in QNet Wallet, pay once, confirm again.',
  guide_short_pc_1: 'Create or import a wallet in the QNet extension and put 1DEV and a little SOL on it.',
  guide_short_pc_2: 'Connect the extension here and activate.',
  guide_short_pc_3: 'Restore the same wallet in QNet Wallet on your phone.',
  guide_short_pc_4: 'In QNet Wallet on your phone, open the "Node" tab and tap "Use this device".',
  guide_short_super_1: 'Create or import a wallet in the QNet extension and put 1DEV and a little SOL on it.',
  guide_short_super_2: 'Connect the extension here and activate a super node.',
  guide_short_super_3: 'Build and start the QNet node software on your server with the code and the wallet\'s recovery phrase.',
  guide_short_super_4: 'The Overview shows the node once the server joins.',
  guide_full: 'See every step with pictures',
  faq_title: 'Good to know',
  faq_one_q: 'How many nodes can I run?',
  faq_one_a: 'One node per wallet: a light node or a super node, chosen once, and the QNet network refuses a second node of either type. A light node runs on one phone or tablet at a time; a computer never runs it. A super node runs on a server and is activated only in the QNet extension.',
  faq_move_q: 'How do I move the node to another phone?',
  faq_move_a: 'Restore the same wallet on the new phone with your 12 words. Then open the "Node" tab in QNet Wallet there and tap "Use this device". The old phone stops: one node runs on one device at a time.',
  faq_code_q: 'What is the activation code for?',
  faq_code_a: 'A receipt of the burn. A light node never needs it typed; a super node\'s server needs it in its settings. Nobody can take anything with it.',
  faq_back_q: 'My phone was off. What now?',
  faq_back_a: 'Turn it on and open QNet Wallet. If My node offers "I\'m back", tap it: the network asks the phone to answer right away.',
  faq_words_q: 'I lost my 12 words.',
  faq_words_a: 'Nobody can restore the wallet without them. While the wallet still opens, show the words in its settings and write them down.',

  // The labels the guide's pictures show: the app's, the extension's and the faucet page's own words
  // (cabinet-guide.test.mjs).
  ui_app_name: 'QNet Wallet',
  ui_app_welcome: 'Get started with QNet',
  ui_app_create_new: 'Create New Wallet',
  ui_app_import: 'Import Existing Wallet',
  ui_app_create: 'Create Wallet',
  ui_app_terms: 'I accept the Terms of Service',
  ui_app_seed_title: 'Save Your Recovery Phrase',
  ui_app_wrote: 'I Wrote It Down',
  ui_app_confirm_title: 'Confirm Your Recovery Phrase',
  ui_app_select_word: 'Select word #{n}',
  ui_app_confirm_create: 'Confirm & Create Wallet',
  ui_app_import_title: 'Import Wallet',
  ui_app_phrase: 'Enter the 12 or 24 word recovery phrase',
  ui_app_share_title: 'Share this wallet\'s addresses',
  ui_app_link_title: 'Link this wallet\'s node to this device',
  ui_app_reserve_title: 'Set up a light node for this wallet',
  ui_app_origin: 'Request through aiqnet.io',
  ui_app_qnet_address: 'QNet address',
  ui_app_solana_address: 'Solana address',
  ui_app_link_node: 'Node',
  ui_app_link_wallet: 'Wallet',
  ui_app_reject: 'Reject',
  ui_app_confirm: 'Confirm',
  ui_app_node_tab: 'Node',
  ui_app_node_balance: 'Node balance:',
  ui_app_use: 'Use this device',
  ui_ext_name: 'QNet Wallet',
  ui_ext_setup_page: 'QNet Wallet setup',
  ui_ext_welcome_lead: 'No wallet in this browser yet.',
  ui_ext_welcome_setup: 'Create or import a wallet',
  ui_ext_setup_welcome: 'Set up QNet Wallet',
  ui_ext_setup_title: 'Write down your recovery phrase',
  ui_ext_create: 'Create a new wallet',
  ui_ext_import: 'Import a wallet',
  ui_ext_written: 'I wrote the words down on paper, in order.',
  ui_ext_continue: 'Continue',
  ui_ext_verify_title: 'Check your backup',
  ui_ext_word: 'Word #{n}',
  ui_ext_check: 'Check',
  ui_ext_password_title: 'Choose a password',
  ui_ext_new_password: 'New password',
  ui_ext_repeat_password: 'Repeat the new password',
  ui_ext_create_wallet: 'Create wallet',
  ui_ext_qnet: 'QNet',
  ui_ext_solana: 'Solana',
  ui_ext_assets: 'Assets',
  ui_ext_receive: 'Receive',
  ui_ext_send: 'Send',
  ui_ext_history: 'History',
  ui_ext_settings: 'Settings',
  ui_ext_activate: 'Activate',
  ui_ext_copy_address: 'Copy address',
  ui_ext_connect_title: 'Connect this site?',
  ui_ext_connect: 'Connect',
  ui_ext_reject: 'Reject',
  ui_ext_activate_title: 'Activate a Light node?',
  ui_ext_activate_super_title: 'Activate a Super node?',
  ui_ext_ack: 'I understand that {amount} 1DEV will be destroyed and that this wallet gets exactly one code.',
  ui_ext_burn: 'Burn {amount} 1DEV',
  ui_ext_claim_title: 'Move node balance to this wallet?',
  ui_ext_move: 'Move to wallet',
  ui_faucet_title: 'Token Faucet',
  ui_faucet_button: 'Get test tokens',

  // The link page (/l)
  l_title: 'Open in the QNet app',
  l_subtitle: 'This address carries a request from aiqnet.io for the QNet app',
  l_button_lead: 'Open this request in QNet Wallet on this device:',
  l_button_note: 'QNet Wallet shows the request before anything happens. Without the app, the button leads to the wallet page.',
  l_lead: 'On a phone or tablet with QNet Wallet, this address opens the app, which shows the request before anything happens. This page opened instead, for one of these reasons:',
  l_reason_missing: 'QNet Wallet is not installed on this device. Install it (see {walletPage}), then tap the button on {nodePage} again.',
  l_wallet_page: 'the wallet page',
  l_reason_update: 'The request needs a newer QNet Wallet. Update it, then tap the button on {nodePage} again.',
  l_reason_embedded: 'The page is open inside another app, such as a messenger. Open it in the device\'s own browser, or show the request\'s QR code on aiqnet.io/node and scan it with the device\'s camera.',
  l_only_yours: 'Only continue in the app with a request you started on aiqnet.io yourself, just now.',

  // Support
  support_title: 'Support',
  support_subtitle: 'QNet Wallet on phones and tablets, and the browser extension',
  support_contact_title: 'Contact',
  support_contact_email: 'Email: {address}',
  support_contact_bugs: 'Bugs and feature requests: {link}',
  support_contact_bugs_link: 'GitHub issues',
  support_contact_community: 'Community: {link}',
  support_contact_docs: 'Documentation: {link}',
  support_never_share: 'Never send your recovery phrase or private key to anyone, including anyone claiming to be support. Nobody who works on QNet will ever ask for it, and nobody can restore a wallet without it.',
  support_lost_title: 'I lost my recovery phrase',
  support_lost: 'There is no recovery. The wallet is non-custodial: the recovery phrase exists only where you wrote it down. If it is gone, the wallet cannot be restored on a new device. While you still have access to the wallet, open Settings, show the phrase and write it down; keep it offline.',
  support_pending_title: 'My transaction shows "Awaiting confirmation" or "Pending"',
  support_pending_lead: 'The network has not confirmed it yet, so the outcome is not known. The wallet keeps asking the chain and updates the history when it knows. Sending the same payment again can pay it twice:',
  support_pending_app: 'In the mobile app, the next send from that wallet asks what to do with the unconfirmed one. Replace it: the new send takes its place, and only one of the two can go through. Send in addition: both can go through.',
  support_pending_extension: 'In the browser extension, the send review lists the unconfirmed transfers and offers to replace one of them (only one of the two can go through); otherwise the new send goes in addition, and all of them can go through.',
  support_pending_once: 'To be charged once, wait until the first transaction is confirmed, or open the address in the explorer and check it, before you send the payment again.',
  support_epochs_title: 'My light node misses epochs',
  support_epochs_lead: 'A light node answers the network\'s status requests while QNet Wallet runs on its device: open, in the background or behind the lock screen. What can delay or skip its answers:',
  support_epochs_closed: 'Closing the app from the list of recent apps, or a force stop: the node then does not answer until the app is opened again.',
  support_epochs_battery: 'Battery restrictions for the app: allow QNet Wallet to run in the background in the device\'s settings. A battery-saving mode can also hold background answers back while it is on.',
  support_epochs_offline: 'The device has to be online at least sometimes. With no connection for a whole four-hour epoch there is nothing to answer the epoch with.',
  support_epochs_apple: 'iPhone and iPad: Background App Refresh has to be on. In Settings → General → Background App Refresh, it must not be Off, and the switch next to QNet Wallet must be on. Without it, and in Low Power Mode, which turns it off, the node answers only while the app is open.',
  support_epochs_android: 'Android: the usual battery setting is enough on most phones. If the Node tab counts fewer epochs than have passed while the phone was online, open Settings → Apps → QNet Wallet and set its battery use to Unrestricted (on some phones: No restrictions). Some phones also need the app allowed to start by itself.',
  support_epochs_sleep: 'An ordinary sleeping device is not a problem: the network repeats its requests during the epoch, and any answer counts that comes before the epoch\'s check closes, about 2.5 minutes before the epoch ends. An answer after that counts for no epoch, not the next one either.',
  support_epochs_wake: 'On {nodePage}, I\'m back on the Overview asks the network to wake the linked device now.',
  support_epochs_wake_link: 'My node',
  support_device_title: 'The node does not run on this device',
  support_device_lead: 'A light node runs on one phone or tablet at a time. If the Node tab says that the node is paused on this device, or that this device can\'t run a node, run it on another phone or tablet: install QNet Wallet there from the app store, open this wallet with its recovery phrase and tap Use this device on the Node tab. The wallet and the node balance are not affected, and the balance can still be moved into the wallet ({rules}).',
  support_device_rules_link: 'Device rules',
  support_move_title: 'The old Android app asks me to install the new QNet Wallet',
  support_move: 'An earlier Android build of QNet Wallet installed from a file is a separate, older app, and its last update asks you to move. Install QNet Wallet from Google Play or from the {walletPage}: it is the same app. Restore the wallet in it with the recovery phrase — the funds are on the chain, not in the app — and remove the old app once the new one shows the wallet. To run the wallet\'s light node in the new app, open its Node tab and choose Use this device.',
  support_move_wallet_link: 'wallet page',
  support_history_title: 'Where is my history',
  support_history: 'The wallet shows history from the aiqnet.io explorer archive together with the freshest data from the nodes. A row opens the transaction in the explorer; a pending row copies its hash instead. If a transfer is missing, open the address in the {explorer} — the chain is the record.',
  support_history_explorer_link: 'explorer',
  support_legal_title: 'Legal',
  support_legal: '{privacy} · {terms}. Publisher: Orrery Group LLC, 30 N Gould St Ste R, Sheridan, WY 82801, United States.',
  support_legal_privacy: 'Privacy Policy',
  support_legal_terms: 'Terms of Use',
  support_form_ref: 'Reference shown in the app',
  support_form_kind: 'What the app shows',
  support_form_note: 'Anything else support should know (optional)',
  support_form_write: 'Write the email',
  support_form_phrase: 'This looks like a recovery phrase. Never send it to anyone, support included: remove it from the note.',
  support_form_ref_missing: 'Enter the 8-character reference the app shows next to its message.',
  support_form_mail_note: 'This opens your email app with the message written; nothing is sent from this page. Without an email app, write to {address} with the reference.',
  support_case_paused: 'The node is paused on this device',
  support_case_cant_run: 'This device can\'t run a node',
  support_case_other: 'Something else about the device check',
} as const;

export type MessageKey = keyof typeof TEXTS;

// {name} placeholders, filled from `vars`; a placeholder without a value stays as written.
export function format(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (whole, name: string) => (Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : whole));
}

// A text by its key; a key looked up by code that has no text shows as the key itself.
export function t(key: MessageKey, vars?: Record<string, string | number>): string {
  return format(TEXTS[key] ?? key, vars);
}

const NUMBERS = new Intl.NumberFormat('en');

// A count or an amount as the texts write it: 1,234.5.
export function number(value: number | bigint): string {
  return NUMBERS.format(value);
}

// A text as its runs and its {name} slots, for a sentence that holds a link.
export function templateParts(template: string): (string | { name: string })[] {
  return template.split(/\{(\w+)\}/).map((part, i) => (i % 2 === 1 ? { name: part } : part)).filter((part) => part !== '');
}

// A page title: its parts, then the site's name.
export function pageTitle(...parts: MessageKey[]): string {
  return [...parts.map((k) => TEXTS[k]), 'QNet'].join(' - ');
}
