[workspace]
members = [
    "core/qnet-core",
    "core/qnet-sharding",
    "core/qnet-consensus", 
    "core/qnet-state",
    "core/qnet-mempool",
    "development/qnet-integration",
    # "infrastructure/qnet-api",
    # "qnet-p2p", 
    # "qnet_node",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["QNet Team"]
license = "MIT"
repository = "https://github.com/qnet/qnet"

[workspace.dependencies]
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
sha2 = "0.10"
rand = "0.8"
async-trait = "0.1"

# Post-quantum cryptography dependencies
pqcrypto = "0.18"
pqcrypto-dilithium = { version = "0.7", features = ["dilithium2"] }
ed25519-dalek = { version = "2.1", features = ["std"] }

# Sharding and consensus dependencies
bincode = "1.3"
blake3 = "1.5"
crossbeam-channel = "0.5"

# Performance and networking
dashmap = "5.5"
parking_lot = "0.12"

# Hardware acceleration
rayon = "1.8"
simd-adler32 = "0.3"
crc32fast = "1.3"

# Memory optimization
mimalloc = "0.1"
jemalloc = "0.5"

# Production-optimized profiles
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
debug-assertions = false
incremental = false
rpath = false

[profile.production]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
debug-assertions = false
incremental = false
rpath = false

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
strip = true

[profile.dev]
opt-level = 1
debug = true
overflow-checks = true
debug-assertions = true
incremental = true

[profile.test]
opt-level = 2
debug = true
overflow-checks = true 