[features]
seeds = false
skip-lint = false

[programs.localnet]
onedev_burn_contract = "4n6wAph553sx32ZkCEt3HdeAnZY28av4sutLdjBB5caq"

[programs.devnet]
onedev_burn_contract = "4n6wAph553sx32ZkCEt3HdeAnZY28av4sutLdjBB5caq"

[programs.mainnet]
onedev_burn_contract = "4n6wAph553sx32ZkCEt3HdeAnZY28av4sutLdjBB5caq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 