// DEVP-R1-02: the light-client pin the SDK compiles in is the mobile app's, and packing the SDK (prepack) refuses a pin
// older than SDK_PIN_MAX_AGE_DAYS: a fresh process walks from it, about 480 steps for every day of its age.
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { checkSdkPin, pinSource, SDK_PIN_MAX_AGE_DAYS } from '../scripts/pin-check.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DAY_MS = 86_400_000;
const shift = (day, days) => new Date(Date.parse(`${day}T00:00:00Z`) + days * DAY_MS).toISOString().slice(0, 10);

describe('the light-client pin at packing', () => {
  const source = pinSource();
  const generated = /Generated by scripts\/ws-pin\.js on (\d{4}-\d{2}-\d{2})/.exec(source)?.[1];

  it('passes on the day it was generated and up to the limit, and fails after', () => {
    assert.ok(generated, 'genesisConsensus.js names the day ws-pin.js wrote the pin');
    assert.equal(SDK_PIN_MAX_AGE_DAYS, 7);
    assert.deepEqual(checkSdkPin({ source, today: generated }), []);
    assert.deepEqual(checkSdkPin({ source, today: shift(generated, SDK_PIN_MAX_AGE_DAYS) }), []);
    const late = checkSdkPin({ source, today: shift(generated, SDK_PIN_MAX_AGE_DAYS + 1) });
    assert.equal(late.length, 1);
    assert.match(late[0], /days old \(at most 7\): run node scripts\/ws-pin\.js --write in applications\/qnet-mobile/);
  });

  it('refuses a pin ws-pin.js did not write, or one not proven from the previous pin', () => {
    assert.match(checkSdkPin({ source: 'export const WS_CHECKPOINT = { index: 5 };', today: generated })[0], /no pin written by scripts\/ws-pin\.js/);
    const bootstrap = source.replace(/provenFrom: \{ index: \d+, hash: '[0-9a-f]{64}' \},/, 'provenFrom: null,');
    assert.notEqual(bootstrap, source);
    assert.match(checkSdkPin({ source: bootstrap, today: generated }).join('\n'), /not proven from a previous pin/);
  });

  it('runs before every pack', () => {
    const pkg = JSON.parse(readFileSync(path.join(HERE, '..', 'package.json'), 'utf8'));
    assert.equal(pkg.scripts.prepack, 'node scripts/pin-check.mjs && node build.mjs');
    assert.equal(pkg.scripts['check:pin'], 'node scripts/pin-check.mjs');
  });
});
