// The light client's weak-subjectivity pin: macroblock K (index and MacroBlock::hash) with the committee-derivation
// anchors of K and K-1, so a walk starts at K instead of at genesis. It is the wallets' release pin, the block between
// the markers kept identical to applications/qnet-mobile/src/config/genesisConsensus.js (made by that app's
// scripts/ws-pin.js, each pin proven from the one before it); the site's tests compare the two. The site proves no
// state at or below K: the pin carries K's committee data, not its state root.
// <ws-pin>
// Generated by scripts/ws-pin.js on 2026-09-25 from 5 genesis nodes (head 2210879; 1260 macroblocks QC-verified from the previous pin 23301).
export const WS_CHECKPOINT = {
  index: 24561,
  hash: '7a0d9348f4ee9c0c493389e747224ba7096a0895f6798a2b456a73665f9ea1b8',
  provenFrom: { index: 23301, hash: '8946cae0d24696f1fba81a679f240b1e5aeefb914eef1e5cbbfa0e9e594530ec' },
  anchors: {
    24561: {
      eligible_raw: '0600000000000000100000000000000067656e657369735f6e6f64655f303031581b0000100000000000000067656e657369735f6e6f64655f303032581b0000100000000000000067656e657369735f6e6f64655f303033581b0000100000000000000067656e657369735f6e6f64655f303034581b0000100000000000000067656e657369735f6e6f64655f303035581b00001b0000000000000073757065725f6e6f64655f63373863333031376134663933343634581b0000',
      beacon: '78de7fea806f5e13a56a4f764d61774ac4da6b1b949c9f7e73c1d014e33c7302',
      registry_root: '1ecd390f1dfb71c5648c8cb44f6f88e0229799dc45e3434d6e5ef3db2faa53fb',
    },
    24560: {
      eligible_raw: '0600000000000000100000000000000067656e657369735f6e6f64655f303031581b0000100000000000000067656e657369735f6e6f64655f303032581b0000100000000000000067656e657369735f6e6f64655f303033581b0000100000000000000067656e657369735f6e6f64655f303034581b0000100000000000000067656e657369735f6e6f64655f303035581b00001b0000000000000073757065725f6e6f64655f63373863333031376134663933343634581b0000',
      beacon: 'e7cd320e2beaebd3bbd452d3b1757ee6a60b2720bb3545eeac6464f371a37480',
      registry_root: '1ecd390f1dfb71c5648c8cb44f6f88e0229799dc45e3434d6e5ef3db2faa53fb',
    },
  },
};
// </ws-pin>

export interface PinAnchor { eligible_raw: string; beacon: string; registry_root: string }

/** The pin's anchor of macroblock `j` (K or K-1), or null. */
export function pinAnchor(j: number): PinAnchor | null {
  const anchors = WS_CHECKPOINT.anchors as Record<string, PinAnchor | undefined>;
  return anchors[String(j)] ?? null;
}
