/// QNet-Native Fungible Token Contract (QEP-20)
///
/// Equivalent to ERC-20 but deployed on QNet's Post-Quantum EVM.
/// All storage operations go through the PQ-EVM state (SLOAD/SSTORE opcodes).
/// Ownership is protected by a Dilithium5 public key stored in account metadata.
///
/// # Bytecode entry-points (ABI function selectors)
///
/// | Selector  | Function                              |
/// |-----------|---------------------------------------|
/// | 0x00000001 | `transfer(to: Address, amount: u64)` |
/// | 0x00000002 | `approve(spender: Address, amount: u64)` |
/// | 0x00000003 | `transfer_from(from, to, amount)`    |
/// | 0x00000004 | `balance_of(owner: Address) → u64`   |
/// | 0x00000005 | `total_supply() → u64`               |
/// | 0x00000006 | `mint(to, amount)` (owner only)      |
/// | 0x00000007 | `burn(amount)`                       |
///
/// This file is human-readable source; compile with `qnet-asmc` to bytecode.

use crate::{Address, ExecutionContext, ExecutionResult, PQEvmInterpreter, GasConfig};

// ─────────────────────────────────────────────────────────────────────────────
// Storage slot layout (follows ERC-20 storage convention)
// ─────────────────────────────────────────────────────────────────────────────

/// Slot 0x00 — total supply
const SLOT_TOTAL_SUPPLY: u64 = 0x00;
/// Slot 0x01 — owner address (lower 8 bytes)
const SLOT_OWNER: u64 = 0x01;
/// Slot 0x10_xxxx — balances[address]  (pseudo-mapping via hash)
const SLOT_BALANCE_PREFIX: u64 = 0x10_0000_0000;
/// Slot 0x20_xxxx — allowances[owner][spender]
const SLOT_ALLOWANCE_PREFIX: u64 = 0x20_0000_0000;

// ─────────────────────────────────────────────────────────────────────────────
// QEP-20 Token bytecode generator
// ─────────────────────────────────────────────────────────────────────────────

/// Produce the init-code bytecode for a QEP-20 token.
///
/// `initial_supply` is minted to `deployer` at construction time.
/// The returned `Vec<u8>` can be passed to `PQEvmInterpreter::create_contract`.
///
/// # Example
/// ```rust
/// let deployer: [u8; 20] = MY_ADDRESS;
/// let bytecode = qep20_init_code(deployer, 1_000_000_000);
/// let interpreter = PQEvmInterpreter::new();
/// let mut state = EVMState::new();
/// let result = interpreter.create_contract(&mut state, &deployer, &bytecode, 0, 1_000_000)?;
/// ```
pub fn qep20_init_code(deployer: Address, initial_supply: u64) -> Vec<u8> {
    // Inline assembly representation; each group is [opcode, ...args]
    let mut code: Vec<u8> = vec![
        // ── Store total supply at slot 0 ──────────────────────────────
        0x67,                          // PUSH8
    ];
    code.extend_from_slice(&initial_supply.to_be_bytes()); // supply value
    code.extend_from_slice(&[
        0x60, 0x00,                    // PUSH1 0x00 (slot)
        0x55,                          // SSTORE  → storage[0] = total_supply
    ]);

    // ── Store owner at slot 1 ─────────────────────────────────────────
    let owner_low8 = u64::from_be_bytes(deployer[12..20].try_into().unwrap_or([0u8; 8]));
    code.push(0x67); // PUSH8
    code.extend_from_slice(&owner_low8.to_be_bytes());
    code.extend_from_slice(&[
        0x60, 0x01,                    // PUSH1 0x01 (slot)
        0x55,                          // SSTORE  → storage[1] = owner
    ]);

    // ── Mint initial supply to deployer ───────────────────────────────
    code.push(0x67); // PUSH8 — balance slot key = SLOT_BALANCE_PREFIX | owner_low8
    let balance_slot = SLOT_BALANCE_PREFIX | (owner_low8 & 0xFFFF);
    code.extend_from_slice(&balance_slot.to_be_bytes());
    code.push(0x67); // PUSH8 — initial_supply
    code.extend_from_slice(&initial_supply.to_be_bytes());
    code.extend_from_slice(&[
        0x55,                          // SSTORE  → balances[deployer] = initial_supply
        // Emit Transfer(address(0), deployer, initial_supply) log
        0x67,
    ]);
    code.extend_from_slice(&initial_supply.to_be_bytes());
    code.extend_from_slice(&[
        0xA1,                          // LOG1 (topic = Transfer selector)
        0x60, 0x00,                    // PUSH1 0x00
        0xF3,                          // RETURN — deployment complete
    ]);
    code
}

/// Runtime dispatcher bytecode (simplified dispatcher for the 7 entry-points).
///
/// In a full implementation this would be generated by the QNet compiler toolchain.
/// Here it illustrates the dispatch pattern for documentation/testing purposes.
pub fn qep20_runtime_bytecode() -> Vec<u8> {
    vec![
        // Read calldata[0..4] as function selector
        0x60, 0x00,    // PUSH1 0
        0x35,          // CALLDATALOAD  → stack: calldata_word
        0x63, 0x00, 0x00, 0x00, 0x04, // PUSH4 4
        0x04,          // DIV  → selector = word >> (32 bits * 7.5) — simplified
        // Dispatch to handler based on selector (1–7)
        0x60, 0x01, 0x13, 0x57, // PUSH1 1; GT; JUMPI <transfer>
        // ... full dispatch table omitted for brevity; see qnet-asmc examples
        0xFE,          // INVALID — unknown selector
    ]
}
