#!/usr/bin/env node
/**
 * The mobile release gate for the light-client pin (MOBNET-R4-07, R4-EXTQ-05, MOBNET-R4-06): run before building a
 * release (`npm run check:release`). It fails when the weak-subjectivity pin in src/config/genesisConsensus.js
 *   - is not one scripts/ws-pin.js generated (the note with the day it did so, directly above WS_CHECKPOINT);
 *   - is older than PIN_MAX_AGE_DAYS: nodes strip the committee signatures of older macroblocks (QC_SIG_RETENTION_MB,
 *     about 15 days), and a phone walks from the pin to the head, one proof per macroblock;
 *   - was not proven from the previous pin (`provenFrom`): a bootstrap pin takes its base anchors from what the genesis
 *     names served at release time, so it passes only with --allow-bootstrap, for a chain that has no pin yet;
 *   - with --online: is further below the head that at least two genesis nodes report than the signature retention.
 * The same age limit as the extension's packaging check (applications/qnet-wallet/scripts/extension.mjs).
 *
 *   node scripts/release-check.js [--online] [--allow-bootstrap]
 */
'use strict';

const fs = require('fs');
const path = require('path');

const CONFIG = path.join(__dirname, '..', 'src', 'config', 'genesisConsensus.js');
const PIN_MAX_AGE_DAYS = 14;
const MACROBLOCK_INTERVAL = 90;
const QC_SIG_RETENTION_MB = 14_880;
const DAY_MS = 86_400_000;
const PIN_RE = /Generated by scripts\/ws-pin\.js on (\d{4}-\d{2}-\d{2})\b[^\n]*\n\s*export const WS_CHECKPOINT = \{\s*index: (\d+),\s*hash: '([0-9a-f]{64})',\s*provenFrom: (null|\{ index: (\d+), hash: '([0-9a-f]{64})' \}),/;

/** { index, hash, generated, provenFrom: { index, hash } | null } from genesisConsensus.js, or null. */
function pinOfSource(source) {
  const m = typeof source === 'string' ? PIN_RE.exec(source) : null;
  if (!m) return null;
  return {
    generated: m[1], index: Number(m[2]), hash: m[3],
    provenFrom: m[4] === 'null' ? null : { index: Number(m[5]), hash: m[6] },
  };
}

/**
 * The problems that stop a release, [] when the pin may ship. `today`: YYYY-MM-DD. `head`: a chain height at least two
 * genesis nodes report (only with --online), or null.
 */
function checkPin({ source, today, head = null, allowBootstrap = false, maxAgeDays = PIN_MAX_AGE_DAYS }) {
  const pin = pinOfSource(source);
  if (!pin) {
    return ['genesisConsensus.js: no pin written by scripts/ws-pin.js (with its date and provenFrom): run node scripts/ws-pin.js --write'];
  }
  const problems = [];
  const age = (Date.parse(`${today}T00:00:00Z`) - Date.parse(`${pin.generated}T00:00:00Z`)) / DAY_MS;
  if (!Number.isFinite(age)) problems.push(`the pin date ${pin.generated} or today ${today} is not a date`);
  else if (age > maxAgeDays) {
    problems.push(`the light-client pin is from ${pin.generated}, ${age} days old (at most ${maxAgeDays}): run node scripts/ws-pin.js --write`);
  }
  if (pin.provenFrom === null) {
    if (!allowBootstrap) {
      problems.push('the light-client pin was not proven from a previous pin (bootstrap: taken from genesis-node agreement): run node scripts/ws-pin.js --write, which proves the new pin from the committed one');
    }
  } else if (!(pin.provenFrom.index < pin.index)) {
    problems.push(`the pin ${pin.index} says it was proven from ${pin.provenFrom.index}, which is not below it`);
  }
  if (head !== null) {
    const behind = Math.floor(head / MACROBLOCK_INTERVAL) - pin.index;
    if (behind > QC_SIG_RETENTION_MB) {
      problems.push(`the pin ${pin.index} is ${behind} macroblocks below the head: older than the nodes keep committee signatures for`);
    }
  }
  return problems;
}

async function agreedHead() {
  // Loaded here only: the config is ES-module source for Metro.
  const nodesSrc = fs.readFileSync(path.join(__dirname, '..', 'src', 'config', 'nodes.js'), 'utf8');
  const names = [...new Set([...nodesSrc.matchAll(/'(https:\/\/node\d+\.aiqnet\.io)'/g)].map((x) => x[1]))];
  const heights = await Promise.all(names.map(async (n) => {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), 15000);
    try {
      const r = await fetch(`${n}/api/v1/height`, { signal: ctl.signal });
      return r.ok ? Number((await r.json()).height) : NaN;
    } catch (_) {
      return NaN;
    } finally {
      clearTimeout(t);
    }
  }));
  const ok = heights.filter((h) => Number.isSafeInteger(h) && h > 0).sort((a, b) => b - a);
  if (ok.length < 2) throw new Error('fewer than two genesis nodes reported a height');
  return ok[1]; // at least two of them are at this height or above
}

async function main() {
  const online = process.argv.includes('--online');
  const allowBootstrap = process.argv.includes('--allow-bootstrap');
  const source = fs.readFileSync(CONFIG, 'utf8');
  const head = online ? await agreedHead() : null;
  const problems = checkPin({ source, today: new Date().toISOString().slice(0, 10), head, allowBootstrap });
  if (problems.length) {
    for (const p of problems) console.error(`release-check: ${p}`);
    process.exit(1);
  }
  console.log('release-check: the light-client pin may ship');
}

if (require.main === module) {
  main().catch((e) => {
    console.error(`release-check: ${e.message}`);
    process.exit(1);
  });
}

module.exports = { checkPin, pinOfSource, PIN_MAX_AGE_DAYS, QC_SIG_RETENTION_MB };
